### ISSUE TITLE
00 -- This is Heavy -- Fahim Faisal

### ISSUE THREAD

**Issue by DevInnovator** [TheIronYard--Orlando/2015--SUMMER--iOS#2]
*[X] Create a Github account
*[X] Find and star the class project
*[X] Read the Home page on the class wiki
*[X] Create a new WIP Issue
*[X] Named 00 -- This is Heavy -- YOUR NAME (where YOUR NAME is your name)
*[X] With this checklist as the description
*[X] Edit your Github profile to provide:
*[X] A picture, so I can recognize your face.
*[X] Your full name, so I can recognize your name.
*[X] A valid public email address, so I can contact you if I need to.
*[X] Complete the "Hello World" Github guide
*[X] Add a link to your new Github repo as a comment on your WIP Issue
*[X] Create a new repository called TIY-Assignments
*[X] Check the box to create an initial README.md file
*[X] Select the CC0 -- "Creative Commons" license for your work
*[X] Add a link to your TIY-Assignments repo as a comment on your WIP Issue
*[X] Complete the "Forking Projects" Github guide
*[X] Add a link to your Fork-and-Spoon repo as a comment on your WIP Issue
*[X] Install Xcode from the Mac App Store. Simply search for Xcode.
*[X] Open Xcode. Click the Xcode menu in the menubar, then choose Preferences. Navigate to the  Downloads tab and install the latest iOS documentation (currently iOS 8.3). Once fully downloaded, the docset should have a small checkmark next to it.
*[X] Install Dash from the Mac App Store. Navigate to the Dash app's preferences and choose the Downloads tab. Install the following docsets:
*[X] iOS 8.3 (or latest, it will find the already loaded set from the step above)
*[X] Swift 1.2 (or latest)
*[X] Objective-C
*[X] Objective-C Blocks
*[X] Xcode
*[X] iOS Design
*[X] Take a screenshot of the Docsets tab in preferences and attach it to your WIP Issue
*[X] Watch The Long Run Videos on Delve.tv
*[X] The Long Game, part 1
*[X] The Long Game, part 2
*[ ] Look at the Prework-A file for instructions on how to complete the Counter app.

Complexity: Medium
Difficulty: Small
Risk: Medium

**Comment by DevInnovator** [comment]
https://github.com/DevInnovator/TIY-Assignments#tiy-assignments

**Comment by DevInnovator** [comment]
https://github.com/DevInnovator/Spoon-Knife#well-hello-there

**Comment by DevInnovator** [comment]
![screen shot 2015-05-31 at 1 14 07 pm](https://cloud.githubusercontent.com/assets/12675241/7902885/2ab83170-0797-11e5-9398-b96421474bcd.png)

**Comment by KevinSFC** [comment]
Hey Fahim!

Edit the issue comment markup so you use asterisks instead of bullets. 
*[X] 

That way, the tick boxes will show up as tasks and will update so Ben sees them.

:-)
-Kevin

**Comment by KevinSFC** [comment]
Sorry, looks like it needs a space between the asterisk and the opening bracket. 
* [X]

**Comment by DevInnovator** [comment]
Thanks man! Very helpful. I was about to start a Gist. Definitely learning by trail and error right now.

**Comment by KevinSFC** [comment]
Same here! You're welcome. I am trying to figure out how to branch the assignment to my assignment repo.
