### ISSUE TITLE
05--Age Calculator--Eli Correa

### ISSUE THREAD

**Issue by EliCorrea** [TheIronYard--Orlando/2015--SUMMER--iOS#27]
https://github.com/EliCorrea/TIY-Assignments/pull/2

**Comment by EliCorrea** [comment]
[ ] StoryBoard Tasks

* [x] Create an app with a main view that shows three labels
* [x] One for the birthdate of the user, another to show current date, and final label to show the user's age
* [x] Provide a button to allow the user to set their birthdate
* [x] Show a view controller with a date picker (When this button is tapped) 
* [x] Add a UIDatePicker label
* [x] Name a custom class to "DatePickerViewController"

**Comment by jcgohlke** [comment]
The app needs to be able to calculate the age of the user.
