### ISSUE TITLE
05 -- Age Calculator -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#29]
https://github.com/jholsapple/TIY-Assignments/pull/2

**Comment by jholsapple** [comment]
# 05 --  Age Calculator

Create an app with a main view that shows three labels: one for the birthdate of the user,  another to show the current date, and a final label to show the user's age. Provide a button to allow the user to set their birthdate. When this button is tapped, show a view controller with a date picker. Once this is shown and the user taps the back button, use a custom delegate to inform the main view of the chosen date (hint: see the Timer app and the OutaTime hw). With the birthdate displayed in the label (formatted nicely using an NSDateFormatter), provide a button on screen that allows the user to calculate their age. Perform the age calculation and then display the age in a label.

### Steps to Success

#### Creation
* [ ] Create a new single view application called "Age Calendar"
* [ ] Create a new view controller with a subclass of UIViewController. Select appropriate name and save.
* [ ] Rename view controller to "CalculateAgeViewController".

#### Storyboard Tasks
* [ ] Embed a Navigation controller to the CalculateAgeViewController
* [ ] Add a new view controller to the right of CalculateAgeViewController
* [ ] Select the custom class for the new view controller
* [ ] Add a UIDatePicker object to the view controller
* [ ] Add 3 labels to the CalculateAgeViewController
* [ ] Set text to "Your birth date", "Today's Date", "Your age"
    * [ ] Create labels to accompany the above labels and fill the text with dates significant to those names.
* [ ] Add a button for the user to set their birth date. 
* [ ] Add another button for the user to calculate their age.
* [ ] Set a segue from "set birth date" button to BirthDatePickerViewController.
* [ ] Make all necessary connections for labels and buttons.
* [ ] Set the segue identifier to "ShowBirthDatePickerSegue"

#### Code Tasks
****to follow****

**Comment by jcgohlke** [comment]
At some point it would be a good idea to go back and use NSDateComponents to split their birthdate apart and use the pieces to calculate their age. You accomplished most of the objectives though. Good job.
