### ISSUE TITLE
09 -- Iron Calendar -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#39]
https://github.com/jholsapple/jholsapple.github.io/pull/2

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments/pull/5

**Comment by jcgohlke** [comment]
Good job. I liked to hear in your journal entry how much you've already learned and how excited you are to learn more in the weeks to come.
