### ISSUE TITLE
12 -- CountOnMe -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#43]
https://github.com/jholsapple/TIY-Assignments/tree/12----CountOnMe/12%20--%20CountOnMe

**Comment by jcgohlke** [comment]
```updateViewWithCurrentCount``` method doesn't appear to exist in the ```CountersTableViewController```. The custom cell class doesn't update the label when the stepper is tapped.
