### ISSUE TITLE
17 -- GitHubFriends -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#55]
# Homework 17

## GitHub Friends - Part 1

Using the app we built today in class, add the following functionality:

In ```NewFriendViewController.m```:
* [x] Create two methods, one for the cancel button and one for the search button. Connect them to their respective buttons with ```addTarget:action:```.
* [x] Place the textfield and two buttons on the screen with ```setFrame:```.
* [x] In the cancel method you create, have the view dismiss itself.
* [x] In the search method you create, have the view dismiss itself. We will replace this with actual internet searching functionality tomorrow in class.

In ```FriendDetailViewController.m```:
* [x] Create 4 UILabel properties
* [x] Initialize UILabel objects for these 4 labels in a custom method called ```configureView``` and set them to their respective property variables.
* [x] Set each label's text property to 4 different values from the ```friendInfo``` dictionary. Use name and company, plus 2 others of your own choosing.
* [x] Set each label's frame.
* [x] Don't forget to add each label as a subview to the main view.

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments/tree/17----GitHubFriends----John-Holsapple/17%20--%20GitHubFriends%20--%20John%20Holsapple

**Comment by jcgohlke** [comment]
Great job.
