### ISSUE TITLE
22 -- Jackpot part Deux -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#60]
#### Storyboard Tasks

* [x] Add a view to the storyboard that shows an interface to pick our winning numbers.
* [x] Add a UIBarButtonItem to the left side of the navigation bar in the root view to allow the user to show the winning number view from the step above.
* [x] Add a button to the winning number view that determines which tickets are winners.
#### Code Tasks

* [x] Create a custom View Controller class to back up the view that was added to the storyboard.
* [ ] Update the Ticket model to include additional state items for tracking the winning status and the dollar amount of winnings.
* [ ] Create a "checkingWinningNumber" type method that iterates over your tickets array and determines which tickets are winners. Follow the rules above about how much each winning type earns.
* [ ] Update the cell handling methods in the LottoNumbersTableViewController to ensure that winning tickets are prominently displayed to the user and the winning amount for that ticket is visible.

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments/tree/master/19%20--%20Forecaster%20--%20John%20Holsapple

**Comment by jcgohlke** [comment]
No code for checking which tickets are winners. Code for showing which ticket cells are winners is not sufficient.
