### ISSUE TITLE
22 -- Jackpot part Deux -- Ian Kunneke

### ISSUE THREAD

**Issue by iankunneke** [TheIronYard--Orlando/2015--SUMMER--iOS#61]

**Comment by iankunneke** [comment]
https://github.com/iankunneke/TIY-Assignmnts/tree/22--JackpotPart2/07--Jackpot/Jackpot

**Comment by jcgohlke** [comment]
No code for determining which tickets are winners. No connections to collect winning picks from the ```WinningViewController```.
