### ISSUE TITLE
24 -- ObjectiveTime -- John Holsapple

### ISSUE THREAD

**Issue by jholsapple** [TheIronYard--Orlando/2015--SUMMER--iOS#65]

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments/tree/24----ObjectiveTime----John-Holsapple/24%20--%20ObjectiveClock%20--%20John%20Holsapple

**Comment by jholsapple** [comment]
https://github.com/jholsapple/TIY-Assignments/tree/24----ObjectiveTime----John-Holsapple/24%20--%20ObjectiveStopwatch%20--%20John%20Holsapple

**Comment by jcgohlke** [comment]
Great job on both app conversions.
